### ISSUE TITLE
Submitting a study with a file fails

### ISSUE THREAD

**Issue by hqcasanova** [EBIBioStudies/BioStudyUISub#102]
This applies to the "subm_templates" branch but, interestingly enough, not to the "master" branch.

The server comes back with a 422 error and the error log in the response contains this entry:
`Path '//submissions/0/section/files/0/file' error: invalid property 'file'`

![error 422](https://user-images.githubusercontent.com/6626603/30368878-790f8682-986a-11e7-979d-a8c8f19806b0.png)

However, the app on the master branch doesn't complain at all.

**Comment by olgamelnichuk** [comment]
I'm afraid #81 isssue should be done first.
You'll need to check the column value type, and if it is 'file' substitute renederer with a file selection box. Have a look how this works in the master (older version) branch. The file selection box component need to be updated in  the subm_templates..

**Comment by hqcasanova** [comment]
Done. The corresponding pull request is  #103.

**Comment by olgamelnichuk** [comment]
it looks good to me

**Comment by hqcasanova** [comment]
Fixed with merged PR #106.

**Comment by hqcasanova** [comment]
Fixed with merged PR #106.
