### ISSUE TITLE
subm_templates: Publication Feature should have PubMedId search column

### ISSUE THREAD

**Issue by olgamelnichuk** [EBIBioStudies/BioStudyUISub#77]
We can create specific PubMed property in the template for the Publication type:
```
{
   type: 'Publication',
   hasPubMedIdColumn: true
}
```
So if feature type has this property then the 'PubMedID' column (not modifieble) should be automatically added; when its value is changed it should automaticaly autofill required publication columns like title, authors, issue, year, page etc.

**Comment by hqcasanova** [comment]
Closing as it has been implemented in #117. Note that instead of using a custom boolean, the `valueType` property will indicate the field is of type `pubmedid`.
