### ISSUE TITLE
subm_templates: it should be possible to delete feature (with default type)

### ISSUE THREAD

**Issue by olgamelnichuk** [EBIBioStudies/BioStudyUISub#91]

**Comment by hqcasanova** [comment]
I assume this is the equivalent of the delete button for sections. Right?

**Comment by olgamelnichuk** [comment]
Almost.. the side bar shows you the list of all (even empty features). The form on the right shows only features that are not empty (has rows or columns).

So, following this logic, the delete button in the side bar should delete feature completely. But the delete button on the right corner of the feature panel should just remove all rows and columns. This issue is about deleting feature completely as there is already a way to delete columns and rows.

**Comment by hqcasanova** [comment]
Ok.

**Comment by olgamelnichuk** [comment]
Reopening.. as it's not finished yet.

**Comment by olgamelnichuk** [comment]
It should be a part of #93
