### ISSUE TITLE
New section added as feature

### ISSUE THREAD

**Issue by hqcasanova** [EBIBioStudies/BioStudyUISub#96]
Applies to subm_templates branch.

The problem crops up when the sidebar's "+ Add..." button is used and is actually two-fold:

* *The section is not added to the existing list of items immediately*: it's only after refresh and navigation to the same submission that the corresponding item shows up. On the right side, however, a new feature is listed with one row and one column.
* *The section is actually a feature*: after refresh, the item created is of type feature, not section. This can be tested by clicking on "Add <name of section>" link; it adds a row to the feature that was rendered instead of the section.

**Comment by olgamelnichuk** [comment]
Yep.. unfortunately it's an artifact.  From the PageTab point of view section and feature are the same until section is not empty (has at least one feature). So when empty section is saved to the PageTab and then transforms back to the submission it becomes a feature.

**Comment by olgamelnichuk** [comment]
There's only one way to keep empty sections in place: make them non empty while in PageTab. E.g. create a feature (with 1 row and 1 column) inside the section when submission is saved to PageTab and delete it when it parsed back to submission. It could be a feature of special type or name...

**Comment by olgamelnichuk** [comment]
The better way probably would be to annotate PageTab sections with special comments, but unfortunately PageTab doesn't allow comments..

**Comment by olgamelnichuk** [comment]
PR #100 fixes the problem. Feel free to discuss it with the team, merge the changes and close this issuie..

**Comment by hqcasanova** [comment]
I would have imagined it is too early in the process for me to even know what to discuss. As I have said before, I am not yet in a position to critically evaluate any pull requests. Until that is the case, I must defer those discussions and subsequent merges to you or the rest of the team. @awaisathar
