### ISSUE TITLE
Deleting rows always throws an error

### ISSUE THREAD

**Issue by hqcasanova** [EBIBioStudies/BioStudyUISub#98]
Regardless of the number of them, trying to delete a given row in any exisiting feature always throws the same error:

```
removeRowAt: The feature [type=<type of feature>] can't have less than one row
```

![screen shot 2017-08-23 at 10 05 03](https://user-images.githubusercontent.com/6626603/29607926-93ba8210-87ea-11e7-9fb9-448bc9650cfd.png)

**Comment by olgamelnichuk** [comment]
it should be fixed now..

**Comment by hqcasanova** [comment]
Confirmed. Closing.
